# Generated by Django 3.0.4 on 2020-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200319_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Experience',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
